// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app-main': string;
  'logo': string;
  'trigger': string;
}
declare const cssExports: CssExports;
export = cssExports;
